site_name: ReviOS Frequently Asked Questions
nav:
    - Home: 'index.md'
    - Before and while installing ReviOS: 'before-install.md'
    - After installing ReviOS: 'after-install.md'
    - Revision website: 'https://www.revi.cc/'
    - Revision Discord: 'https://discord.gg/962y4pU'
theme:
  name: material
  language: en
  logo: img/revision_crop.png
  favicon: img/revision_crop.png
  palette: 
    scheme: slate
    primary: red
    accent: red
  font:
    text: Inter
    code: DM Mono
  features:
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - toc.follow
    #- toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tilde
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/310497849274007553
      name: Dawe24#1229
    - icon: material/web
      link: https://www.revi.cc/
      name: Revision website
    - icon: fontawesome/brands/discord
      link: https://discord.gg/962y4pU
      name: Revision Discord
