site_name: ReviOS Frequently Asked Questions
site_url: https://dkovacs24.github.io/ReviOS_faq/
nav:
    - Home: 'index.md'
    - Before and while installing ReviOS: 'before-install.md'
    - After installing ReviOS: 'after-install.md'
    - ReviOS website: 'https://www.revi.cc/'
    - ReviOS Discord: 'https://discord.gg/962y4pU'
theme:
  name: material
  language: en
  logo: img/revision_crop.png
  favicon: img/revision_crop.png
  palette: 
    scheme: slate
    primary: red
    accent: red
  font:
    text: Cantarell
    code: Cantarell
  features:
    #- navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.instant
    - toc.follow
    #- toc.integrate
markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
