site_name: ReviOS Frequently Asked Questions
copyright: Neither the creator and maintainer of this website, nor the team behind Revision and ReviOS is responsible for your PC, your data and files, your actions and what you do based on this website's information and advice given on the Discord server. Use ReviOS at your own risk.
nav:
    - Home: 'index.md'
    - ReviOS related questions: 'related.md'
    - Not ReviOS related questions: 'not-related.md'
    - How to install ReviOS: 'install.md'
    - How to install drivers: 'drivers.md'
    - Revision website: 'https://www.revi.cc/'
    - Revision Discord: 'https://discord.gg/962y4pU'
theme:
  name: material
  language: en
  logo: img/revision_crop.png
  favicon: img/revision_crop.png
  palette: 
    scheme: slate
    primary: red
    accent: deep orange
  font:
   text: Open Sans
   code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.indexes
    # - navigation.expand
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - toc.follow
    # - toc.integrate
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
      # toc_depth: 3
  - tables
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  generator: true
  social:
    - icon: octicons/person-16
      link: https://discord.com/users/310497849274007553
      name: Dawe24#1229
    - icon: material/web
      link: https://www.revi.cc/
      name: Revision website
    - icon: fontawesome/brands/discord
      link: https://discord.gg/962y4pU
      name: Revision Discord
plugins:
  - search
  - redirects:
      redirect_maps: 
        'after-install.md': 'index.md'
        'before-install.md': 'index.md'
        'discord.md': 'https://discord.gg/962y4pU'
  - git-revision-date